# Generated by Django 3.0.2 on 2020-02-01 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Police',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('date_registered', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=30)),
            ],
        ),
    ]
