# Generated by Django 3.0.2 on 2020-02-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField(auto_now_add=True)),
                ('event_report', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='report_images')),
                ('location_lat', models.FloatField()),
                ('location_lng', models.FloatField()),
                ('status', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
