# Generated by Django 3.0.2 on 2020-02-02 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20200202_1520'),
        ('report', '0002_report_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.User'),
        ),
    ]
