# Generated by Django 3.0.2 on 2020-02-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20200202_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='user_id',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
