# Generated by Django 3.0.2 on 2020-02-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20200202_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='event_time',
            field=models.DateTimeField(),
        ),
    ]
